config/routes.rb
Rails.application.routes.draw do
  resources :drinks, only: [:index, :show]
  resources :user_drinks, except: [:create]
  post 'user_drinks/:id', to: "user_drinks#create", as: "user_drink_create"
  devise_for :users
  root to: 'drinks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  # has_many :user_drinks
  # has_many :users, through: :user_drinks

  # has_many :event_drinks
  # has_many :events, through: :event_drinks

  validates :name, presence: true
  validates :volume, presence: true
  validates :alcohol_rate, presence: true
  validates :alcohol_unit, presence: true

  # validates :photo, presence: true
  before_validation :set_alcohol_unit

  private
    def set_alcohol_unit
      self.alcohol_unit = self.volume * self.alcohol_rate / 100
    end


end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_drinks
  has_many :drinks, through: :event_drinks

  has_many :user_events
  has_many :users, through: :user_events
end

app/models/event_drink.rb
class EventDrink < ApplicationRecord
  belongs_to :event
  belongs_to :drink
  validates :event, presence: true
  validates :drink, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_drinks, dependent: :destroy
  has_many :drinks, through: :user_drinks

  has_many :user_events
  has_many :events, through: :user_events

  validates :email, presence: true, uniqueness: true
end

app/models/user_drink.rb
class UserDrink < ApplicationRecord
  belongs_to :user
  belongs_to :drink
  validates :user, presence: true
  validates :drink, presence: true
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :user, presence: true
  validates :event, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def index
    @drinks = Drink.all
  end

  def show
    @drink = Drink.find(params[:id])
  end

  private

  def drink_params
    params.require(:drink).permit(:id)
  end
end

app/controllers/user_drinks_controller.rb
class UserDrinksController < ApplicationController
  before_action :set_user_drink, only: [:edit, :destroy]

  def index
    @user_drinks = UserDrink.where(user_id: current_user).order(created_at: :desc)
    @drunk_level = total_alcohol_blood_rate(@user_drinks, Time.now)
    @drunk_status = drunk_status(@drunk_level)
    @weekly_drinks = weekly_drinks(@user_drinks)
  end

  def show
  end

  def new

  end

  def create
    user_id = current_user.id
    @user_drink = UserDrink.new(user_id: user_id, drink_id: params[:id])
    @user_drink.save
    redirect_to user_drinks_path
  end

  def edit
  end

  def destroy
    @user_drink.destroy
    redirect_to user_drinks_path
  end

  def total_alcohol_blood_rate(user_drinks, time)
    h24_drinks(user_drinks)
    @drunk_level = 0
    @day_drinks.each do |user_drink|
      @drunk_level += alcohol_blood_rate_per_drink(user_drink, time)
    end
    @drunk_level
  end

  def drunk_status(drunk_level)
    case drunk_level
    when 5.to_f...7.to_f
      @drunk_status = "very_bad"
    when 3.to_f...5.to_f
      @drunk_status = "toasted"
    when 2.to_f...3.to_f
      @drunk_status = "drunk"
    when 1.to_f...2.to_f
      @drunk_status = "very_tipsy"
    when 0.5.to_f...1.to_f
      @drunk_status = "tipsy"
    when 0.0001.to_f...0.5.to_f
      @drunk_status = "OK"
    when drunk_level == 0.to_f
      @drunk_status = "sober"
    else
      @drunk_status = "dead"
    end
  end

  def alcohol_blood_rate_per_drink(user_drink, time)
    elapsed_time = time - user_drink.created_at
    # Erik Matteo Prochet Widmark formula: 0.8 is ethanol density, 0.7 the diffusion coefficient for male, 0.6 for female,72 is weight in kg
    climax = user_drink.drink.volume * user_drink.drink.alcohol_rate / 10 * 0.8  / (0.7 * 72)
    #calculate how much alcohol has been integrated to the body (drink is drunk in 15mn, 30mn to reach the top => 2700 s)
    if elapsed_time <= 2700
      # 0.8 is ethanol density, 0.7 the diffusion coefficient for male, 0.6 for female,72 is weight in kg
      climax * (elapsed_time / 2700)
    else
      [0, climax - ((0.15 * (elapsed_time - 2700) / 3600))].max
    end
  end

  def h24_drinks(user_drinks)
    @day_drinks = user_drinks.where("created_at > ?", 1.days.ago)
    @day_drinks_counter = user_drinks.where("created_at > ?", 1.days.ago).length
  end



  def weekly_drinks(user_drinks)
    @weekly_drinks = user_drinks.where("created_at > ?", 7.days.ago)
  end

  private

  def set_user_drink
    @user_drink = UserDrink.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/user_drinks_helper.rb
module UserDrinksHelper
end

app/views/drinks/index.html.haml
%h1 Drinks#index
= link_to "View everything I have drunk", user_drinks_path, class: "btn btn-primary"
.card-deck
  - counter = 0
  - @drinks.each do |drink|
    .card.card-margin
      = image_tag "default_drink.png", class:"card-img-top"
      .card-body
        %h5.card-title= drink.name
      .card-footer
        %p.card-text
          = drink.volume
          cl
        %p.card-text
          = drink.alcohol_rate
          \%
      .card-footer
        = link_to "Add", user_drink_create_path(drink), method: :post, class: "btn btn-success"
    / Force next card to break to new line every 3 card
    - counter += 1
    - if counter % 4 == 0
      .w-100

app/views/drinks/show.html.haml
%h1= @drink.name
%h2
  = @drink.volume
  cl
%h2
  = @drink.alcohol_rate
  \%
= link_to "Back", drinks_path, class: "btn btn-secondary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drunkr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user_drinks/create.html.erb
<h1>UserDrinks#create</h1>
<p>Find me in app/views/user_drinks/create.html.erb</p>

app/views/user_drinks/destroy.html.erb
<h1>UserDrinks#destroy</h1>
<p>Find me in app/views/user_drinks/destroy.html.erb</p>

app/views/user_drinks/index.html.haml
%h1 Dashboard
= link_to "Add a drink", drinks_path, class: "btn btn-success float-right"
%h2= "#{@drunk_level.round(2)} g/L, you are #{@drunk_status}"
%h3
  Your had
  = succeed "drinks" do
    %strong
      = @day_drinks_counter
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th{:scope => "col"} Drink
        %th{:scope => "col"} Drunk at
        %th{:scope => "col"} Edit
        %th{:scope => "col"} Delete
    %tbody
      - @day_drinks.each do |day_drink|
        %tr
          %th{:scope => "row"}= day_drink.drink.name
          %td= day_drink.created_at
          %td= link_to "Edit", user_drink_path(day_drink), class: "btn btn-primary"
          %td= link_to "Delete", user_drink_path(day_drink), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
%h3 Your drinking history
.table-responsive
  %table.table.table-striped
    %thead
      %tr
        %th{:scope => "col"} Drink
        %th{:scope => "col"} Drunk at
        %th{:scope => "col"} Edit
        %th{:scope => "col"} Delete
    %tbody
      - @user_drinks.each do |user_drink|
        %tr
          %th{:scope => "row"}= user_drink.drink.name
          %td= user_drink.created_at
          %td= link_to "Edit", user_drink_path(user_drink), class: "btn btn-primary"
          %td= link_to "Delete", user_drink_path(user_drink), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

app/views/user_drinks/new.html.erb
<h1>UserDrinks#new</h1>
<p>Find me in app/views/user_drinks/new.html.erb</p>

app/views/user_drinks/show.html.erb
<h1>UserDrinks#show</h1>
<p>Find me in app/views/user_drinks/show.html.erb</p>